version: '3.4'

services:
  bitchutescrapper:
    image: bitchutescrapper
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m main "]
    ports:
      - 5678:5678
    container_name: bitchutescrapper
    environment:
      MONGODB_DATABASE: bitchutescrapperdb
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: ytsemfake
      MONGODB_HOSTNAME: mongodb
    volumes:
      - ./src/data:/src/data
    depends_on:
       - mongodb
    networks:
      - mongo-compose-network

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ytsemfake
      MONGO_INITDB_DATABASE: bitchutescrapperdb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /tmp/log/mongo
    ports:
      - "27017:27017"
    volumes:
      - ./src/data/db:/data/db
    networks:
      - mongo-compose-network

  bitchute_video_scrapper:
    image: bitchute_video_scrapper
    build:
      context: .
      dockerfile: ./DockerfileVideoScrapper
    container_name: bitchute_video_scrapper
    restart: unless-stopped
    environment:
      MONGODB_DATABASE: bitchutescrapperdb
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: ytsemfake
      MONGODB_HOSTNAME: mongodb
    volumes:
      - ./src/data:/src/data
    depends_on:
        - mongodb
    networks:
      - mongo-compose-network    

  bitchute_channel_scrapper:
    image: bitchute_channel_scrapper
    build:
      context: .
      dockerfile: ./DockerfileChannelScrapper
    container_name: bitchute_channel_scrapper
    restart: unless-stopped
    environment:
      MONGODB_DATABASE: bitchutescrapperdb
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: ytsemfake
      MONGODB_HOSTNAME: mongodb
    volumes:
      - ./src/data:/src/data
    depends_on:
        - mongodb
    networks:
      - mongo-compose-network       

  bitchute_live_video_data:
    image: bitchute_live_video_data
    build:
      context: .
      dockerfile: ./DockerfileExtractLiveVideoData
    container_name: bitchute_live_video_data
    restart: unless-stopped
    environment:
      MONGODB_DATABASE: bitchutescrapperdb
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: ytsemfake
      MONGODB_HOSTNAME: mongodb
    volumes:
      - ./src/data:/src/data
    depends_on:
        - mongodb
    networks:
      - mongo-compose-network      

  bitchute_live_channel_data:
    image: bitchute_live_channel_data
    build:
      context: .
      dockerfile: ./DockerfileExtractLiveChannelData
    container_name: bitchute_live_channel_data
    restart: unless-stopped
    environment:
      MONGODB_DATABASE: bitchutescrapperdb
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: ytsemfake
      MONGODB_HOSTNAME: mongodb
    volumes:
      - ./src/data:/src/data
    depends_on:
        - mongodb
    networks:
      - mongo-compose-network         

networks: 
    mongo-compose-network:
      driver: bridge

 
 